### ISSUE TITLE
Min requirements

### ISSUE THREAD

**Issue by JulianLeviston** [oakes/Nightmod#6]
After purchasing on Apple App Store (support FTW), went to install on our family (2007) mac mini for housemate's kid, and it said the gfx support was missing and couldn't install it. Would be good if minimum requirements other than Java 7 were mentioned on any of the sites, or on the App Store itself. Would consider updating computer, but I'm not sure what the actual requirements *are* - is it that it needs to have more than onboard graphics? Tried to download separately to see if that would actually install anyway, but that failed too - wouldn't open.

**Comment by oakes** [comment]
I believe the requirement is OS X 10.6.8 or above and OpenGL 2 or above. I think the mac mini may only support OpenGL 1. To see the specific error message, try running the JAR version from the terminal. I'll adjust the description the next time I update the app store version.

**Comment by JulianLeviston** [comment]
Thank you.

And also... YOU ROCK! <3
