### ISSUE TITLE
Add rainbow parens

### ISSUE THREAD

**Issue by ddossot** [oakes/Nightmod#8]
Rainbow parens provide a nice visual cue about where you are in nesting them:

![screenshot from 2015-07-23 09 08 36](https://cloud.githubusercontent.com/assets/119028/8855587/c6961f92-311a-11e5-8a6b-a2de64c335d7.png)

Plus it's kind of cute, which can make nightmod even more fun :wink:

**Comment by oakes** [comment]
Since this functionality comes from Nightcode I'll close this issue. See the relevant ticket on that repo: https://github.com/oakes/Nightcode/issues/17
